version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    update-type: "security"
