repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  # Local Django checks (fast)
  - repo: local
    hooks:
      - id: django-system-check
        name: Django system check
        entry: bash -c 'python manage.py check --fail-level=ERROR'
        language: system
        types: [python]
      - id: django-migrations-check
        name: Django missing migrations check
        entry: bash -c 'python manage.py makemigrations --check --dry-run'
        language: system
        types: [python]

  # Run tests on push (not every commit)
  - repo: local
    hooks:
      - id: tests-on-push
        name: Run test.sh (pre-push)
        entry: bash -c './test.sh'
        language: system
        pass_filenames: false
        always_run: true
