line-length = 80
indent-width = 4

exclude = [
    "coverage/",
    "**/migrations/**",
    "static/",
    "templates/",
]

[lint]
select = [
    "E",
    "F",
    "B",
    "DJ",
    "I",
    "N",
    "UP",
    "SIM",
    "T20",
    "S",
    "ANN",
    "D",
    "TD",
    "C4",
]
ignore = ["D203", "D212"]
fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
"config/**" = ["D"]
"core/management/commands/**" = ["ANN", "D"]
"core/views/**" = ["ANN", "D"]
"core/models/**" = ["ANN", "D"]              # TODO : remove ANN rule from core/models
"core/admin/**" = ["ANN", "D"]
"tests/**" = ["ANN", "D"]


[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = "dynamic"
