# Generated by Django 5.2.4 on 2025-08-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.PositiveIntegerField()),
                ("week", models.PositiveIntegerField()),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("postseason", "Postseason"),
                            ("both", "Both"),
                            ("allstar", "Allstar"),
                            ("spring_regular", "Spring Regular"),
                            ("spring_postseason", "Spring Postseason"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                ("neutral_site", models.BooleanField(default=False)),
                (
                    "home_classification",
                    models.CharField(
                        choices=[
                            ("fbs", "FBS"),
                            ("fcs", "FCS"),
                            ("ii", "Division II"),
                            ("iii", "Division III"),
                        ],
                        max_length=20,
                    ),
                ),
                ("home_score", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "away_classification",
                    models.CharField(
                        choices=[
                            ("fbs", "FBS"),
                            ("fcs", "FCS"),
                            ("ii", "Division II"),
                            ("iii", "Division III"),
                        ],
                        max_length=20,
                    ),
                ),
                ("away_score", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "away_conference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="away_matches",
                        to="core.conference",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="core.team",
                    ),
                ),
                (
                    "home_conference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_matches",
                        to="core.conference",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="core.team",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="core.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("completed", False),
                            models.Q(
                                ("completed", True),
                                ("home_score__isnull", False),
                                ("away_score__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="completed_requires_scores",
                    )
                ],
            },
        ),
    ]
