# Generated by Django 5.2.4 on 2025-07-31 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, max_length=100, null=True)),
                ("abbreviation", models.CharField(max_length=20, unique=True)),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fbs", "FBS"),
                            ("fcs", "FCS"),
                            ("ii", "Division II"),
                            ("iii", "Division III"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "conference",
                "verbose_name_plural": "conferences",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="team",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="core.conference",
            ),
        ),
    ]
