# Generated by Django 5.2.4 on 2025-07-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="teamalternativename",
            constraint=models.UniqueConstraint(
                fields=("team", "name"), name="team_name_unique"
            ),
        ),
    ]
