# Generated by Django 5.2.4 on 2025-07-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(default="tmp", unique=True),
            preserve_default=False,
        ),
    ]
