# Generated by Django 5.2.4 on 2025-07-30 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="core.venue",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamalternativename",
            constraint=models.UniqueConstraint(
                fields=("team", "name"), name="team_name_unique"
            ),
        ),
    ]
