# Generated by Django 5.2.4 on 2025-08-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="attendance",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fbs", "FBS"),
                    ("fcs", "FCS"),
                    ("ii", "Division II"),
                    ("iii", "Division III"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fbs", "FBS"),
                    ("fcs", "FCS"),
                    ("ii", "Division II"),
                    ("iii", "Division III"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="season_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("postseason", "Postseason"),
                    ("both", "Both"),
                    ("allstar", "Allstar"),
                    ("spring_regular", "Spring Regular"),
                    ("spring_postseason", "Spring Postseason"),
                ],
                max_length=20,
            ),
        ),
    ]
