# Generated by Django 5.2.4 on 2025-07-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["school"]},
        ),
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ["name"]},
        ),
    ]
