# Generated by Django 5.2.4 on 2025-08-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_match_attendance_alter_match_away_classification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlickoRating",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "team_id",
                        "season",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("season", models.PositiveIntegerField()),
                ("previous_rating", models.FloatField(default=1500)),
                ("previous_rd", models.FloatField(default=350)),
                ("previous_vol", models.FloatField(default=0.11)),
                ("rating", models.FloatField()),
                ("rd", models.FloatField()),
                ("vol", models.FloatField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_history",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "glicko rating",
                "verbose_name_plural": "glicko ratings",
                "ordering": ["season", "team_id"],
                "indexes": [
                    models.Index(
                        fields=["team", "season"], name="core_glicko_team_id_a129b4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "season"),
                        name="unique_team_glicko_rating_per_season",
                    )
                ],
            },
        ),
    ]
