# Generated by Django 5.2.4 on 2025-07-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_team_options_alter_venue_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='division',
        ),
    ]
