# Generated by Django 5.2.4 on 2025-07-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_team_division"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["school"],
                "verbose_name": "team",
                "verbose_name_plural": "teams",
            },
        ),
        migrations.AlterModelOptions(
            name="teamalternativename",
            options={
                "verbose_name": "team alternative name",
                "verbose_name_plural": "team alternative names",
            },
        ),
        migrations.AlterModelOptions(
            name="teamlogo",
            options={"verbose_name": "team logo", "verbose_name_plural": "team logos"},
        ),
        migrations.AlterModelOptions(
            name="venue",
            options={
                "ordering": ["name"],
                "verbose_name": "venue",
                "verbose_name_plural": "venues",
            },
        ),
    ]
