# Generated by Django 5.2.4 on 2025-07-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_team_division"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fbs", "FBS"),
                    ("fcs", "FCS"),
                    ("ii", "Division II"),
                    ("iii", "Division III"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
