# Generated by Django 5.2.4 on 2025-08-05 11:04

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_team_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="glickorating",
            name="rating_change",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("rating"), "-", models.F("previous_rating")
                ),
                output_field=models.FloatField(),
            ),
        ),
    ]
