# Generated by Django 5.2.4 on 2025-08-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_glickorating_rating_change"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glickorating",
            options={
                "ordering": ["season", "week", "team_id"],
                "verbose_name": "glicko rating",
                "verbose_name_plural": "glicko ratings",
            },
        ),
        migrations.RemoveConstraint(
            model_name="glickorating",
            name="unique_team_glicko_rating_per_season",
        ),
        migrations.RemoveIndex(
            model_name="glickorating",
            name="core_glicko_team_id_a129b4_idx",
        ),
        migrations.AddField(
            model_name="glickorating",
            name="week",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="glickorating",
            name="pk",
            field=models.CompositePrimaryKey(
                "team_id",
                "season",
                "week",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddIndex(
            model_name="glickorating",
            index=models.Index(
                fields=["team", "season", "week"], name="core_glicko_team_id_f835f2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="glickorating",
            constraint=models.UniqueConstraint(
                fields=("team", "season", "week"),
                name="unique_team_glicko_rating_per_week",
            ),
        ),
    ]
