# Generated by Django 5.2.4 on 2025-08-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_glickorating_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="glickorating",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fbs", "FBS"),
                    ("fcs", "FCS"),
                    ("ii", "Division II"),
                    ("iii", "Division III"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="glickorating",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="glicko_ratings",
                to="core.conference",
            ),
        ),
    ]
