# Generated by Django 5.2.4 on 2025-08-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_glickorating_classification_glickorating_conference"),
    ]

    operations = [
        migrations.AddField(
            model_name="glickorating",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
