# Generated by Django 5.2.4 on 2025-08-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_glickorating_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glickorating",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fbs", "FBS"),
                    ("fcs", "FCS"),
                    ("ii", "Division II"),
                    ("iii", "Division III"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="glickorating",
            name="season",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="glickorating",
            name="week",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
