# Generated by Django 5.2.4 on 2025-08-07 16:54

from django.db import migrations, models
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    Conference = apps.get_model("core", "Conference")
    for conference in Conference.objects.all():
        base_slug = slugify(conference.name)
        slug = base_slug
        counter = 1
        while Conference.objects.filter(slug=slug).exclude(pk=conference.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        conference.slug = slug
        conference.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_glickorating_classification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="slug",
            field=models.SlugField(max_length=50, unique=True, null=True),
        ),
        migrations.RunPython(populate_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="conference",
            name="slug",
            field=models.SlugField(max_length=50, unique=True),
        ),
    ]
