# Generated by Django 5.2.4 on 2025-08-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_conference_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
