# Generated by Django 5.2.4 on 2025-08-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_venue_country_code_alter_venue_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='classification',
            field=models.CharField(blank=True, choices=[('fbs', 'FBS'), ('fcs', 'FCS'), ('ii', 'Division II'), ('iii', 'Division III')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
