# Generated by Django 5.2.4 on 2025-08-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_conference_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glickorating',
            name='classification',
            field=models.CharField(blank=True, choices=[('fbs', 'FBS'), ('fcs', 'FCS'), ('ii', 'Division II'), ('iii', 'Division III')], db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
