# Generated by Django 5.2.4 on 2025-08-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_glickorating_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='classification',
            field=models.CharField(blank=True, choices=[('fbs', 'FBS'), ('fcs', 'FCS'), ('ii', 'Division II'), ('iii', 'Division III')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='mascot',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
