# Generated by Django 5.2.4 on 2025-08-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_team_abbreviation_alter_team_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_classification',
            field=models.CharField(blank=True, choices=[('fbs', 'FBS'), ('fcs', 'FCS'), ('ii', 'Division II'), ('iii', 'Division III')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='home_classification',
            field=models.CharField(blank=True, choices=[('fbs', 'FBS'), ('fcs', 'FCS'), ('ii', 'Division II'), ('iii', 'Division III')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
