# Generated by Django 5.2.4 on 2025-08-10 22:35

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_match_away_classification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EloRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating_before", models.FloatField(default=1500)),
                ("rating_after", models.FloatField()),
                (
                    "rating_change",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("rating_after"),
                            "-",
                            models.F("rating_before"),
                        ),
                        output_field=models.FloatField(),
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elo_ratings",
                        to="core.match",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elo_ratings",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "elo rating",
                "verbose_name_plural": "elo ratings",
                "ordering": ["match_id", "team_id"],
                "indexes": [
                    models.Index(
                        fields=["team", "match"],
                        name="core_elorat_team_id_ac314b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "match"),
                        name="unique_team_elo_per_match",
                    )
                ],
            },
        ),
    ]
