# Generated by Django 5.2.4 on 2025-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_elorating"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(("home_team", models.F("away_team")), _negated=True),
                name="home_away_team_diff",
            ),
        ),
    ]
